create table email_attachment (
	EMAIL_ATTACHMENT_ID LONG not null primary key,
	EMAIL_REMINDER_ID LONG,
	ATTACHMENT_FILE_NAME VARCHAR(250) null,
	ATTACHMENT_FILE_TEXT BLOB,
	CREATE_USER_ID VARCHAR(50) null,
	CREATE_TIME_STAMP DATE null,
	LAST_UPDATE_USER_ID VARCHAR(50) null,
	LAST_UPDATE_TIMESTAMP DATE null
);

create table email_reminder (
	EMAIL_REMINDER_ID LONG not null primary key,
	SUBMITTER_NM VARCHAR(150) null,
	SUBMITTER_EMAIL_ID VARCHAR(100) null,
	REMINDER_NBR INTEGER,
	SCHED_TS DATE null,
	EMAIL_SUBJECT_TXT VARCHAR(250) null,
	EMAIL_BODY_TXT STRING null,
	STAT_CD VARCHAR(75) null,
	CREAT_USR_ID VARCHAR(50) null,
	CREAT_TS DATE null,
	LST_UPDT_USR_ID VARCHAR(50) null,
	LST_UPDT_TS DATE null
);