/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.me2.mhn.portlet.model.impl;

import com.ihg.me2.mhn.portlet.model.SecurityNotification;
import com.ihg.me2.mhn.portlet.service.SecurityNotificationLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SecurityNotification service. Represents a row in the &quot;Security_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecurityNotificationImpl}.
 * </p>
 *
 * @author vishal.rangras
 * @see SecurityNotificationImpl
 * @see com.ihg.me2.mhn.portlet.model.SecurityNotification
 * @generated
 */
public abstract class SecurityNotificationBaseImpl
	extends SecurityNotificationModelImpl implements SecurityNotification {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a security notification model instance should use the {@link SecurityNotification} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SecurityNotificationLocalServiceUtil.addSecurityNotification(this);
		}
		else {
			SecurityNotificationLocalServiceUtil.updateSecurityNotification(this);
		}
	}
}