/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.me2.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmailReminder service. Represents a row in the &quot;email_reminder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.me2.model.impl.EmailReminderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.me2.model.impl.EmailReminderImpl}.
 * </p>
 *
 * @author vishal.rangras
 * @see EmailReminder
 * @see com.ihg.me2.model.impl.EmailReminderImpl
 * @see com.ihg.me2.model.impl.EmailReminderModelImpl
 * @generated
 */
public interface EmailReminderModel extends BaseModel<EmailReminder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a email reminder model instance should use the {@link EmailReminder} interface instead.
	 */

	/**
	 * Returns the primary key of this email reminder.
	 *
	 * @return the primary key of this email reminder
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this email reminder.
	 *
	 * @param primaryKey the primary key of this email reminder
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the email reminder ID of this email reminder.
	 *
	 * @return the email reminder ID of this email reminder
	 */
	public long getEmailReminderId();

	/**
	 * Sets the email reminder ID of this email reminder.
	 *
	 * @param emailReminderId the email reminder ID of this email reminder
	 */
	public void setEmailReminderId(long emailReminderId);

	/**
	 * Returns the submitter name of this email reminder.
	 *
	 * @return the submitter name of this email reminder
	 */
	@AutoEscape
	public String getSubmitterName();

	/**
	 * Sets the submitter name of this email reminder.
	 *
	 * @param submitterName the submitter name of this email reminder
	 */
	public void setSubmitterName(String submitterName);

	/**
	 * Returns the submitter email ID of this email reminder.
	 *
	 * @return the submitter email ID of this email reminder
	 */
	@AutoEscape
	public String getSubmitterEmailId();

	/**
	 * Sets the submitter email ID of this email reminder.
	 *
	 * @param submitterEmailId the submitter email ID of this email reminder
	 */
	public void setSubmitterEmailId(String submitterEmailId);

	/**
	 * Returns the reminder number of this email reminder.
	 *
	 * @return the reminder number of this email reminder
	 */
	public int getReminderNumber();

	/**
	 * Sets the reminder number of this email reminder.
	 *
	 * @param reminderNumber the reminder number of this email reminder
	 */
	public void setReminderNumber(int reminderNumber);

	/**
	 * Returns the schedule timestamp of this email reminder.
	 *
	 * @return the schedule timestamp of this email reminder
	 */
	public Date getScheduleTimestamp();

	/**
	 * Sets the schedule timestamp of this email reminder.
	 *
	 * @param scheduleTimestamp the schedule timestamp of this email reminder
	 */
	public void setScheduleTimestamp(Date scheduleTimestamp);

	/**
	 * Returns the email subject text of this email reminder.
	 *
	 * @return the email subject text of this email reminder
	 */
	@AutoEscape
	public String getEmailSubjectText();

	/**
	 * Sets the email subject text of this email reminder.
	 *
	 * @param emailSubjectText the email subject text of this email reminder
	 */
	public void setEmailSubjectText(String emailSubjectText);

	/**
	 * Returns the email body text of this email reminder.
	 *
	 * @return the email body text of this email reminder
	 */
	@AutoEscape
	public String getEmailBodyText();

	/**
	 * Sets the email body text of this email reminder.
	 *
	 * @param emailBodyText the email body text of this email reminder
	 */
	public void setEmailBodyText(String emailBodyText);

	/**
	 * Returns the status code of this email reminder.
	 *
	 * @return the status code of this email reminder
	 */
	@AutoEscape
	public String getStatusCode();

	/**
	 * Sets the status code of this email reminder.
	 *
	 * @param statusCode the status code of this email reminder
	 */
	public void setStatusCode(String statusCode);

	/**
	 * Returns the create user ID of this email reminder.
	 *
	 * @return the create user ID of this email reminder
	 */
	@AutoEscape
	public String getCreateUserId();

	/**
	 * Sets the create user ID of this email reminder.
	 *
	 * @param createUserId the create user ID of this email reminder
	 */
	public void setCreateUserId(String createUserId);

	/**
	 * Returns the create timestamp of this email reminder.
	 *
	 * @return the create timestamp of this email reminder
	 */
	public Date getCreateTimestamp();

	/**
	 * Sets the create timestamp of this email reminder.
	 *
	 * @param createTimestamp the create timestamp of this email reminder
	 */
	public void setCreateTimestamp(Date createTimestamp);

	/**
	 * Returns the last update user ID of this email reminder.
	 *
	 * @return the last update user ID of this email reminder
	 */
	@AutoEscape
	public String getLastUpdateUserId();

	/**
	 * Sets the last update user ID of this email reminder.
	 *
	 * @param lastUpdateUserId the last update user ID of this email reminder
	 */
	public void setLastUpdateUserId(String lastUpdateUserId);

	/**
	 * Returns the last update timestamp of this email reminder.
	 *
	 * @return the last update timestamp of this email reminder
	 */
	public Date getLastUpdateTimestamp();

	/**
	 * Sets the last update timestamp of this email reminder.
	 *
	 * @param lastUpdateTimestamp the last update timestamp of this email reminder
	 */
	public void setLastUpdateTimestamp(Date lastUpdateTimestamp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmailReminder emailReminder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmailReminder> toCacheModel();

	@Override
	public EmailReminder toEscapedModel();

	@Override
	public EmailReminder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}