/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.me2.service.base;

import com.ihg.me2.model.EmailAttachment;
import com.ihg.me2.model.EmailAttachmentAttachmentFileTextBlobModel;
import com.ihg.me2.service.EmailAttachmentLocalService;
import com.ihg.me2.service.persistence.EmailAttachmentPersistence;
import com.ihg.me2.service.persistence.EmailReminderPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Session;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the email attachment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ihg.me2.service.impl.EmailAttachmentLocalServiceImpl}.
 * </p>
 *
 * @author vishal.rangras
 * @see com.ihg.me2.service.impl.EmailAttachmentLocalServiceImpl
 * @see com.ihg.me2.service.EmailAttachmentLocalServiceUtil
 * @generated
 */
public abstract class EmailAttachmentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EmailAttachmentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ihg.me2.service.EmailAttachmentLocalServiceUtil} to access the email attachment local service.
	 */

	/**
	 * Adds the email attachment to the database. Also notifies the appropriate model listeners.
	 *
	 * @param emailAttachment the email attachment
	 * @return the email attachment that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EmailAttachment addEmailAttachment(EmailAttachment emailAttachment)
		throws SystemException {
		emailAttachment.setNew(true);

		return emailAttachmentPersistence.update(emailAttachment);
	}

	/**
	 * Creates a new email attachment with the primary key. Does not add the email attachment to the database.
	 *
	 * @param EMAIL_ATTACHMENT_ID the primary key for the new email attachment
	 * @return the new email attachment
	 */
	@Override
	public EmailAttachment createEmailAttachment(long EMAIL_ATTACHMENT_ID) {
		return emailAttachmentPersistence.create(EMAIL_ATTACHMENT_ID);
	}

	/**
	 * Deletes the email attachment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param EMAIL_ATTACHMENT_ID the primary key of the email attachment
	 * @return the email attachment that was removed
	 * @throws PortalException if a email attachment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EmailAttachment deleteEmailAttachment(long EMAIL_ATTACHMENT_ID)
		throws PortalException, SystemException {
		return emailAttachmentPersistence.remove(EMAIL_ATTACHMENT_ID);
	}

	/**
	 * Deletes the email attachment from the database. Also notifies the appropriate model listeners.
	 *
	 * @param emailAttachment the email attachment
	 * @return the email attachment that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EmailAttachment deleteEmailAttachment(
		EmailAttachment emailAttachment) throws SystemException {
		return emailAttachmentPersistence.remove(emailAttachment);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(EmailAttachment.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return emailAttachmentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ihg.me2.model.impl.EmailAttachmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return emailAttachmentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ihg.me2.model.impl.EmailAttachmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return emailAttachmentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return emailAttachmentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return emailAttachmentPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public EmailAttachment fetchEmailAttachment(long EMAIL_ATTACHMENT_ID)
		throws SystemException {
		return emailAttachmentPersistence.fetchByPrimaryKey(EMAIL_ATTACHMENT_ID);
	}

	/**
	 * Returns the email attachment with the primary key.
	 *
	 * @param EMAIL_ATTACHMENT_ID the primary key of the email attachment
	 * @return the email attachment
	 * @throws PortalException if a email attachment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public EmailAttachment getEmailAttachment(long EMAIL_ATTACHMENT_ID)
		throws PortalException, SystemException {
		return emailAttachmentPersistence.findByPrimaryKey(EMAIL_ATTACHMENT_ID);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return emailAttachmentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the email attachments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ihg.me2.model.impl.EmailAttachmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of email attachments
	 * @param end the upper bound of the range of email attachments (not inclusive)
	 * @return the range of email attachments
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<EmailAttachment> getEmailAttachments(int start, int end)
		throws SystemException {
		return emailAttachmentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of email attachments.
	 *
	 * @return the number of email attachments
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getEmailAttachmentsCount() throws SystemException {
		return emailAttachmentPersistence.countAll();
	}

	/**
	 * Updates the email attachment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param emailAttachment the email attachment
	 * @return the email attachment that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EmailAttachment updateEmailAttachment(
		EmailAttachment emailAttachment) throws SystemException {
		return emailAttachmentPersistence.update(emailAttachment);
	}

	@Override
	public EmailAttachmentAttachmentFileTextBlobModel getAttachmentFileTextBlobModel(
		Serializable primaryKey) throws SystemException {
		Session session = null;

		try {
			session = emailAttachmentPersistence.openSession();

			return (com.ihg.me2.model.EmailAttachmentAttachmentFileTextBlobModel)session.get(EmailAttachmentAttachmentFileTextBlobModel.class,
				primaryKey);
		}
		catch (Exception e) {
			throw emailAttachmentPersistence.processException(e);
		}
		finally {
			emailAttachmentPersistence.closeSession(session);
		}
	}

	/**
	 * Returns the email attachment local service.
	 *
	 * @return the email attachment local service
	 */
	public com.ihg.me2.service.EmailAttachmentLocalService getEmailAttachmentLocalService() {
		return emailAttachmentLocalService;
	}

	/**
	 * Sets the email attachment local service.
	 *
	 * @param emailAttachmentLocalService the email attachment local service
	 */
	public void setEmailAttachmentLocalService(
		com.ihg.me2.service.EmailAttachmentLocalService emailAttachmentLocalService) {
		this.emailAttachmentLocalService = emailAttachmentLocalService;
	}

	/**
	 * Returns the email attachment remote service.
	 *
	 * @return the email attachment remote service
	 */
	public com.ihg.me2.service.EmailAttachmentService getEmailAttachmentService() {
		return emailAttachmentService;
	}

	/**
	 * Sets the email attachment remote service.
	 *
	 * @param emailAttachmentService the email attachment remote service
	 */
	public void setEmailAttachmentService(
		com.ihg.me2.service.EmailAttachmentService emailAttachmentService) {
		this.emailAttachmentService = emailAttachmentService;
	}

	/**
	 * Returns the email attachment persistence.
	 *
	 * @return the email attachment persistence
	 */
	public EmailAttachmentPersistence getEmailAttachmentPersistence() {
		return emailAttachmentPersistence;
	}

	/**
	 * Sets the email attachment persistence.
	 *
	 * @param emailAttachmentPersistence the email attachment persistence
	 */
	public void setEmailAttachmentPersistence(
		EmailAttachmentPersistence emailAttachmentPersistence) {
		this.emailAttachmentPersistence = emailAttachmentPersistence;
	}

	/**
	 * Returns the email reminder local service.
	 *
	 * @return the email reminder local service
	 */
	public com.ihg.me2.service.EmailReminderLocalService getEmailReminderLocalService() {
		return emailReminderLocalService;
	}

	/**
	 * Sets the email reminder local service.
	 *
	 * @param emailReminderLocalService the email reminder local service
	 */
	public void setEmailReminderLocalService(
		com.ihg.me2.service.EmailReminderLocalService emailReminderLocalService) {
		this.emailReminderLocalService = emailReminderLocalService;
	}

	/**
	 * Returns the email reminder remote service.
	 *
	 * @return the email reminder remote service
	 */
	public com.ihg.me2.service.EmailReminderService getEmailReminderService() {
		return emailReminderService;
	}

	/**
	 * Sets the email reminder remote service.
	 *
	 * @param emailReminderService the email reminder remote service
	 */
	public void setEmailReminderService(
		com.ihg.me2.service.EmailReminderService emailReminderService) {
		this.emailReminderService = emailReminderService;
	}

	/**
	 * Returns the email reminder persistence.
	 *
	 * @return the email reminder persistence
	 */
	public EmailReminderPersistence getEmailReminderPersistence() {
		return emailReminderPersistence;
	}

	/**
	 * Sets the email reminder persistence.
	 *
	 * @param emailReminderPersistence the email reminder persistence
	 */
	public void setEmailReminderPersistence(
		EmailReminderPersistence emailReminderPersistence) {
		this.emailReminderPersistence = emailReminderPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.ihg.me2.model.EmailAttachment",
			emailAttachmentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.ihg.me2.model.EmailAttachment");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return EmailAttachment.class;
	}

	protected String getModelClassName() {
		return EmailAttachment.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = emailAttachmentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.ihg.me2.service.EmailAttachmentLocalService.class)
	protected com.ihg.me2.service.EmailAttachmentLocalService emailAttachmentLocalService;
	@BeanReference(type = com.ihg.me2.service.EmailAttachmentService.class)
	protected com.ihg.me2.service.EmailAttachmentService emailAttachmentService;
	@BeanReference(type = EmailAttachmentPersistence.class)
	protected EmailAttachmentPersistence emailAttachmentPersistence;
	@BeanReference(type = com.ihg.me2.service.EmailReminderLocalService.class)
	protected com.ihg.me2.service.EmailReminderLocalService emailReminderLocalService;
	@BeanReference(type = com.ihg.me2.service.EmailReminderService.class)
	protected com.ihg.me2.service.EmailReminderService emailReminderService;
	@BeanReference(type = EmailReminderPersistence.class)
	protected EmailReminderPersistence emailReminderPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EmailAttachmentLocalServiceClpInvoker _clpInvoker = new EmailAttachmentLocalServiceClpInvoker();
}