/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.me2.mhn.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SecurityNotification service. Represents a row in the &quot;Security_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.me2.mhn.portlet.model.impl.SecurityNotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.me2.mhn.portlet.model.impl.SecurityNotificationImpl}.
 * </p>
 *
 * @author vishal.rangras
 * @see SecurityNotification
 * @see com.ihg.me2.mhn.portlet.model.impl.SecurityNotificationImpl
 * @see com.ihg.me2.mhn.portlet.model.impl.SecurityNotificationModelImpl
 * @generated
 */
public interface SecurityNotificationModel extends BaseModel<SecurityNotification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a security notification model instance should use the {@link SecurityNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this security notification.
	 *
	 * @return the primary key of this security notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this security notification.
	 *
	 * @param primaryKey the primary key of this security notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the notification ID of this security notification.
	 *
	 * @return the notification ID of this security notification
	 */
	public long getNotificationId();

	/**
	 * Sets the notification ID of this security notification.
	 *
	 * @param notificationId the notification ID of this security notification
	 */
	public void setNotificationId(long notificationId);

	/**
	 * Returns the gm screenname of this security notification.
	 *
	 * @return the gm screenname of this security notification
	 */
	@AutoEscape
	public String getGmScreenname();

	/**
	 * Sets the gm screenname of this security notification.
	 *
	 * @param gmScreenname the gm screenname of this security notification
	 */
	public void setGmScreenname(String gmScreenname);

	/**
	 * Returns the gm name of this security notification.
	 *
	 * @return the gm name of this security notification
	 */
	@AutoEscape
	public String getGmName();

	/**
	 * Sets the gm name of this security notification.
	 *
	 * @param gmName the gm name of this security notification
	 */
	public void setGmName(String gmName);

	/**
	 * Returns the gm email of this security notification.
	 *
	 * @return the gm email of this security notification
	 */
	@AutoEscape
	public String getGmEmail();

	/**
	 * Sets the gm email of this security notification.
	 *
	 * @param gmEmail the gm email of this security notification
	 */
	public void setGmEmail(String gmEmail);

	/**
	 * Returns the pc screenname of this security notification.
	 *
	 * @return the pc screenname of this security notification
	 */
	@AutoEscape
	public String getPcScreenname();

	/**
	 * Sets the pc screenname of this security notification.
	 *
	 * @param pcScreenname the pc screenname of this security notification
	 */
	public void setPcScreenname(String pcScreenname);

	/**
	 * Returns the pc name of this security notification.
	 *
	 * @return the pc name of this security notification
	 */
	@AutoEscape
	public String getPcName();

	/**
	 * Sets the pc name of this security notification.
	 *
	 * @param pcName the pc name of this security notification
	 */
	public void setPcName(String pcName);

	/**
	 * Returns the pc email of this security notification.
	 *
	 * @return the pc email of this security notification
	 */
	@AutoEscape
	public String getPcEmail();

	/**
	 * Sets the pc email of this security notification.
	 *
	 * @param pcEmail the pc email of this security notification
	 */
	public void setPcEmail(String pcEmail);

	/**
	 * Returns the sec pc screenname of this security notification.
	 *
	 * @return the sec pc screenname of this security notification
	 */
	@AutoEscape
	public String getSecPcScreenname();

	/**
	 * Sets the sec pc screenname of this security notification.
	 *
	 * @param secPcScreenname the sec pc screenname of this security notification
	 */
	public void setSecPcScreenname(String secPcScreenname);

	/**
	 * Returns the sec pc name of this security notification.
	 *
	 * @return the sec pc name of this security notification
	 */
	@AutoEscape
	public String getSecPcName();

	/**
	 * Sets the sec pc name of this security notification.
	 *
	 * @param secPcName the sec pc name of this security notification
	 */
	public void setSecPcName(String secPcName);

	/**
	 * Returns the sec pc email of this security notification.
	 *
	 * @return the sec pc email of this security notification
	 */
	@AutoEscape
	public String getSecPcEmail();

	/**
	 * Sets the sec pc email of this security notification.
	 *
	 * @param secPcEmail the sec pc email of this security notification
	 */
	public void setSecPcEmail(String secPcEmail);

	/**
	 * Returns the fops screenname of this security notification.
	 *
	 * @return the fops screenname of this security notification
	 */
	@AutoEscape
	public String getFopsScreenname();

	/**
	 * Sets the fops screenname of this security notification.
	 *
	 * @param fopsScreenname the fops screenname of this security notification
	 */
	public void setFopsScreenname(String fopsScreenname);

	/**
	 * Returns the fops name of this security notification.
	 *
	 * @return the fops name of this security notification
	 */
	@AutoEscape
	public String getFopsName();

	/**
	 * Sets the fops name of this security notification.
	 *
	 * @param fopsName the fops name of this security notification
	 */
	public void setFopsName(String fopsName);

	/**
	 * Returns the fops email of this security notification.
	 *
	 * @return the fops email of this security notification
	 */
	@AutoEscape
	public String getFopsEmail();

	/**
	 * Sets the fops email of this security notification.
	 *
	 * @param fopsEmail the fops email of this security notification
	 */
	public void setFopsEmail(String fopsEmail);

	/**
	 * Returns the holidex code of this security notification.
	 *
	 * @return the holidex code of this security notification
	 */
	@AutoEscape
	public String getHolidexCode();

	/**
	 * Sets the holidex code of this security notification.
	 *
	 * @param holidexCode the holidex code of this security notification
	 */
	public void setHolidexCode(String holidexCode);

	/**
	 * Returns the hotel name of this security notification.
	 *
	 * @return the hotel name of this security notification
	 */
	@AutoEscape
	public String getHotelName();

	/**
	 * Sets the hotel name of this security notification.
	 *
	 * @param hotelName the hotel name of this security notification
	 */
	public void setHotelName(String hotelName);

	/**
	 * Returns the impacted of this security notification.
	 *
	 * @return the impacted of this security notification
	 */
	@AutoEscape
	public String getImpacted();

	/**
	 * Sets the impacted of this security notification.
	 *
	 * @param impacted the impacted of this security notification
	 */
	public void setImpacted(String impacted);

	/**
	 * Returns the start date of this security notification.
	 *
	 * @return the start date of this security notification
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this security notification.
	 *
	 * @param startDate the start date of this security notification
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this security notification.
	 *
	 * @return the end date of this security notification
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this security notification.
	 *
	 * @param endDate the end date of this security notification
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SecurityNotification securityNotification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SecurityNotification> toCacheModel();

	@Override
	public SecurityNotification toEscapedModel();

	@Override
	public SecurityNotification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}